### ISSUE TITLE
  can change  sassc to sass ?

### ISSUE THREAD

**Issue by xingzheone** [openweb-nl/open-bank-mark#1]
npm install -g sass 
I think it will be easier . 

```
  :sass {:src              "resources/app/stylesheets"
         :output-directory "resources/public/css"
         :source-maps      false
         :command          :sass} ;因为sassc不好安装,所以这里试验下 sass
```

**Comment by gklijs** [comment]
I'll tried it a couple of times but got errors. On Mac sassc is just `brew install sassc` on Linux is a bit more cumbersome, but the .travis.yml as inspiration. Another option would be to just include the css, which make it even more easy and having less dependencies but feels wrong.
I'm quite happy it's now working correctly both on Mac and on TravisCi so don't really feel like changing it again. Please let me now what your thoughts are.

**Comment by xingzheone** [comment]
tks, No big problem.  now I change  build-and-copy-frontend.sh  little 
```
#!/usr/bin/env bash

lein clean &&
#lein sass once &&
sass resources/app/stylesheets/open-bank.sass resources/public/css/open-bank.css &&
lein cljsbuild once min &&
cp -rf resources/public .
```
it's work good .

another problem is  jdk 11  

; :javac-options ["-target" "11" "-source" "11"]    I commented  
jdk8 is ok

**Comment by gklijs** [comment]
True, jdk 11 is not really needed, but I would much rather that java 11 becomes the default instead of 8. Also the docker images use 11 so there might be some byte code optimisation missing.
